### ISSUE TITLE
Prequisites?

### ISSUE THREAD

**Issue by rbarkas** [kintel/aisdecoder#1]
I did npm install aisdecoder

When I try to run your sample code I get:
var decoder = new AisDecoder;
                               ^
ReferenceError: AisDecoder is not defined
    at Object.<anonymous> (/home/sop/aisDecoderTest.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Any suggestions?

**Comment by crueda** [comment]
i have the following error when i execute npm install aisdecoder:

pm WARN package.json log@1.4.0 No repository field.
|
> aisdecoder@0.0.2 install /Users/Carlos/Workspace/SUMO/API_REST/node_modules/aisdecoder
> node-gyp rebuild

  CXX(target) Release/obj.target/aisdecoder/src/addon.o
../src/addon.cpp:41:39: error: too few arguments to function call, single argument 'isolate' was not specified
  Handle<Object> aisobj = Object::New();
                          ~~~~~~~~~~~ ^
/Users/Carlos/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/addon.cpp:42:23: error: no member named 'New' in 'v8::String'
  aisobj->Set(String::New("type"), String::New(ais_typestring(ais->type)));
              ~~~~~~~~^


...


...


any idea? :(


Thanks
